---
output: html_fragment
---

#### The Normal Distribution: Copper/Sulfur Ratio in Copper (I) Sulfide

**Exercise 1**. The figure on the right is a histogram for 62 measurements of *x*, the ratio of the moles of copper to the moles of sulfur in samples of Cu~*x*~S prepared by igniting Cu and S.  The value of *x* in Cu~*x*~S is considered continuous. What does it mean to say that *x* is continuous and why does this experiment yield continuous data?

**Exercise 2**. A histogram shows the frequency for a range (bin) of possible outcomes. The bin on the far-left, for example, shows that one of the 62 trials has a value for *x* in the range 1.760--1.775. Why do we need to bin the data to create a useful histogram?

**Exercise 3**. The data in this experiment follows a normal distribution, which is given as
$$p(x) = \frac{1}{\sigma \sqrt{2 \pi}}e^{-(x - \mu)^2/(2 \sigma^2)}$$
where $p(x)$ is the probability of a given outcome, $\mu$ is the mean, and $\sigma$ is the standard deviation. The dashed line overlaid on the histogram is the normal distribution---as frequencies instead of probabilities---for the mean and standard deviation set by the sliders. Adjust the sliders to explore how the mean and standard deviation affect the normal distribution's overall shape. Explain how your observations are consistent with the equation for a normal distribution.

**Exercise 4**. Adjust the mean and the standard deviation to provide the best fit of the normal distribution equation to the data. When satisfied with your fit, download the data as a spreadsheet and calculate the experiment's mean and standard deviation, Compare these to your estimated values from fitting the normal distribution's equation to the data.

**Exercise 5**. A normal distribution assumes all samples come from the same population. Suppose these 62 samples come from two populations, one where sulfur was used in excess and one where it was not. Describe the shape of the resulting histogram.
