---
output: html_document
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {
    extensions: ["[Contrib]/mhchem/mhchem.js"]
}
});
MathJax.Hub.Config({ 
        "HTML-CSS": { scale: 90 }, 
        SVG: { linebreaks: { automatic:true } }, 
 });
</script>
```

<!-- text for activity 2 -->

#### The Poisson Distribution: Emission of Beta Particles from ^40^K

The figure on the right is a barplot that shows the number of beta particles emitted by a sample of ^40^K during 365 consecutive 7-s intervals. In some intervals, no beta particles were emitted; in other intervals, as many as 13 beta particles were emitted.

**Exercise 2**. Although a barplot and a histogram look similar, they are not interchangeable. A histogram is useful for continuous data and a barplot is useful for discrete data. Why are the results of beta emission considered discrete instead of continuous?

**Exercise 1**. The data in this experiment follow a Poisson distribution in which the probability of a particular outcome, $p(x)$, in a fixed period of time is given by the equation
$$p(x) = \frac{\lambda^x e^{-\lambda}}{x!}$$
where $\lambda$ is the average rate of beta emission and where the exclamation point indicates the factorial. For the Cu~*x*~S data we drew the theoretical distribution as a smooth line, but here we show only a set of points connected by line segments. Explain why we can display the normal distribution as a smooth line, but cannot do so with a Poisson distribution.

**Exercise 3**. How does the shape of the Poisson distribution change as you adjust the value of $\lambda$ from 0 to 13?

**Exercise 4**. Use the slider to determine the value of $\lambda$ for this data. Use your value of $\lambda$ to calculate the probability that a single beta particle is emitted, *p(x = 1)*. Explain how to convert this probability into a number of events and compare this result to the data in the figure.

**Exercise 5**. The mean for a Poisson distribution is equal to $\lambda$ and its standard deviation is equal to $\sqrt{\lambda}$. Report the mean and standard deviation for this data using your value for $\lambda$ and then download the data and check your result by calculating the actual mean and standard deviation.
